---

- name: Create new AD domain in a new forest on DC
  ansible.windows.win_domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: domain_install

- name: Reboot after promotion
  ansible.windows.win_reboot:
  when: domain_install.reboot_required