---

- name: Copy desktop wallpaper
  win_copy:
    src: files/DesktopWallpaper.jpg
    dest: C:\Users\Public\Pictures\DesktopWallpaper.jpg

- name: Copy bginfo configuration
  win_copy:
    src: files/bginfo.bgi
    dest: C:\Users\Public\bginfo.bgi

- name: Install utilities 
  win_chocolatey:
    name:
    - NotepadPlusPlus
    - GoogleChrome
    - bginfo
    state: present
    ignore_checksums: true

- name: Configure bginfo as autorun
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: 'C:\ProgramData\chocolatey\bin\bginfo.exe c:\users\public\bginfo.bgi /silent /timer:0 /nolicprompt'