---
# Run common tasks on all machines in parallel
- hosts: windows
  roles:
    - common

# Configure the DC to prepare the domain
- hosts: dc
  roles:
    - domain

# Domain-join clients and run post-domain configuration in parallel
- hosts: windows
  strategy: free
  tasks:
    - include_role:
        name: winserv2019
      when: "'winserv2019' in group_names"
    - include_role: 
        name: win10
      when: "'win10' in group_names"
    - include_role:
        name: dc
      when: "'dc' in group_names"