---

# Join domain
- name: Configure DNS settings
  win_dns_client:
      adapter_names: Ethernet
      ipv4_addresses:
      - 10.13.37.10
      - 8.8.8.8

- name: Join machine to domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    hostname: "win10"
    domain_admin_user: "{{ ansible_user }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required


# Clean up Windows stuff from the taskbar
- name: Ensure 'Search' unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

- name: Ensure Task View, Chat and Cortana are unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - ShowTaskViewButton
    - TaskbarDa
    - TaskbarMn

- name: Ensure 'News and Interests' unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
    name: EnableFeeds
    data: 0
    type: dword
    state: present

- name: Ensure 'People' unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
    name: PeopleBand
    data: 0
    type: dword

- name: Ensure 'Edge', 'Store' other built-in shortcuts unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
    name: Favorites
    state: absent